# Generated by Django 3.1.12 on 2021-12-14 16:01

import logging

from django.db import migrations, models

from integration import error_codes

logger = logging.getLogger(__name__)

ERROR_VALUES = [
    (
        error_codes.ACCESS_REVOKED,
        'ACCESS_REVOKED',
        'Access Revoked',
        'Access Revoked for Projects',
        '<p>Please check that you have the correct credentials and re-configure the'
        ' integration.</p>',
    ),
]


def adding_access_revoked_error(apps, schema_editor):
    error_catalogue_model = apps.get_model('integration', 'ErrorCatalogue')
    for error in ERROR_VALUES:
        code, name, reason, description, default_message = error
        error_created, created = error_catalogue_model.objects.update_or_create(
            code=code,
            defaults={
                'error': name,
                'failure_reason_mail': reason,
                'description': description,
                'default_message': default_message,
                'send_email': True,
            },
        )
        if created:
            logger.info(f'Integration error {error_created.code} created.')


class Migration(migrations.Migration):
    dependencies = [
        ('integration', '0041_add_default_error_catalogue_for_jira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionaccount',
            name='error_code',
            field=models.CharField(
                choices=[
                    ('000', 'None'),
                    ('001', 'Other'),
                    ('002', 'Insufficient Permissions'),
                    ('003', 'Missing Github Organization'),
                    ('004', 'Denial Of Consent'),
                    ('005', 'Insufficient Config Data'),
                    ('006', 'Invalid Client Credentials'),
                    ('007', 'AWS error'),
                    ('008', 'Expired account'),
                    ('009', 'Azure error'),
                    ('010', 'Google Cloud (GCP) error'),
                    ('011', 'Provider Server Error'),
                    ('012', 'Resource not found'),
                    ('013', 'API call exceeded rate limit due to too many requests'),
                    ('014', 'Github App is not installed on the organization'),
                    ('015', 'Provider Graphql API Error'),
                    ('016', 'Connection Time Out'),
                    ('017', 'Default GraphQL Error'),
                    ('018', 'Access Revoked'),
                ],
                default='000',
                max_length=20,
            ),
        ),
        migrations.RunPython(adding_access_revoked_error),
    ]
